import type { Mission } from "../types";

export const missions: Mission[] = [
  {
    id: 1,
    startDate: new Date("2026-04-29"),
    endDate: new Date("2026-05-08"),
    name: "Orbital Relay Alpha",
    rocket: "Falcon 9",
    target: "Low Earth Orbit",
    status: "running",
    type: "cargo",
  },
  {
    id: 2,
    startDate: new Date("2026-11-10"),
    endDate: new Date("2026-11-18"),
    name: "Deep Space Mapper",
    rocket: "Falcon Heavy",
    target: "Kepler-90 c",
    status: "upcoming",
    type: "research",
  },
  {
    id: 3,
    startDate: new Date("2026-11-22"),
    endDate: new Date("2026-11-30"),
    name: "Lunar Base Supply",
    rocket: "Starship",
    target: "Moon",
    status: "running",
    type: "cargo",
  },
  {
    id: 4,
    startDate: new Date("2026-12-05"),
    endDate: new Date("2026-12-12"),
    name: "Europa Scanner",
    rocket: "Explorer Heavy",
    target: "Europa",
    status: "upcoming",
    type: "exploration",
  },
  {
    id: 5,
    startDate: new Date("2026-04-28"),
    endDate: new Date("2026-05-22"),
    name: "Crew Transfer CT-7",
    rocket: "SLS",
    target: "ISS",
    status: "upcoming",
    type: "crewed",
  },
  {
    id: 6,
    startDate: new Date("2026-04-04"),
    endDate: new Date("2026-06-08"),
    name: "Asteroid Mining Test",
    rocket: "Starship",
    target: "Asteroid Belt",
    status: "running",
    type: "research",
  },
  {
    id: 7,
    startDate: new Date("2027-01-15"),
    endDate: new Date("2027-01-25"),
    name: "Mars Habitat Prep",
    rocket: "Starship",
    target: "Mars",
    status: "upcoming",
    type: "cargo",
  },
  {
    id: 8,
    startDate: new Date("2026-04-30"),
    endDate: new Date("2026-06-07"),
    name: "Solar Observatory",
    rocket: "Falcon 9",
    target: "Solar Orbit",
    status: "running",
    type: "research",
  },
  {
    id: 9,
    startDate: new Date("2027-02-12"),
    endDate: new Date("2027-02-20"),
    name: "Titan Exploration Probe",
    rocket: "Falcon Heavy",
    target: "Titan",
    status: "running",
    type: "exploration",
  },
  {
    id: 10,
    startDate: new Date("2027-03-01"),
    endDate: new Date("2027-03-10"),
    name: "Crew Mission CM-12",
    rocket: "SLS",
    target: "Moon",
    status: "upcoming",
    type: "crewed",
  },
];

export const completedMissions: Mission[] = [
  {
    id: 1,
    startDate: new Date("2026-05-16"),
    endDate: new Date("2026-05-20"),
    name: "FalconSat",
    rocket: "Falcon 1",
    target: "Kepler-442 b",
    status: "success",
    type: "cargo",
  },
  {
    id: 2,
    startDate: new Date("2026-06-02"),
    endDate: new Date("2026-06-03"),
    name: "Dragon Demo",
    rocket: "Falcon 9",
    target: "Kepler-186 f",
    status: "aborted",
    type: "cargo",
  },
  {
    id: 3,
    startDate: new Date("2026-06-18"),
    endDate: new Date("2026-06-25"),
    name: "Starlink Batch 12",
    rocket: "Falcon 9",
    target: "Low Earth Orbit",
    status: "success",
    type: "exploration",
  },
  {
    id: 4,
    startDate: new Date("2026-07-01"),
    endDate: new Date("2026-07-10"),
    name: "Explorer IS1",
    rocket: "Explorer Heavy",
    target: "Kepler-452 b",
    status: "success",
    type: "research",
  },
  {
    id: 5,
    startDate: new Date("2026-07-14"),
    endDate: new Date("2026-07-15"),
    name: "Cargo Resupply CRS-3",
    rocket: "Falcon 9",
    target: "ISS",
    status: "aborted",
    type: "exploration",
  },
  {
    id: 6,
    startDate: new Date("2026-08-03"),
    endDate: new Date("2026-08-12"),
    name: "Voyager X",
    rocket: "Starship",
    target: "Kepler-22 b",
    status: "success",
    type: "exploration",
  },
  {
    id: 7,
    startDate: new Date("2026-08-19"),
    endDate: new Date("2026-08-28"),
    name: "Lunar Surveyor",
    rocket: "SLS",
    target: "Moon",
    status: "success",
    type: "crewed",
  },
  {
    id: 8,
    startDate: new Date("2026-09-05"),
    endDate: new Date("2026-09-06"),
    name: "Mars Cargo 1",
    rocket: "Starship",
    target: "Mars",
    status: "aborted",
    type: "exploration",
  },
  {
    id: 9,
    startDate: new Date("2026-09-21"),
    endDate: new Date("2026-10-01"),
    name: "Deep Space Probe",
    rocket: "Falcon Heavy",
    target: "Kepler-62 e",
    status: "success",
    type: "cargo",
  },
  {
    id: 10,
    startDate: new Date("2026-10-10"),
    endDate: new Date("2026-10-20"),
    name: "Habitat Deployment",
    rocket: "Starship",
    target: "Kepler-1649 c",
    status: "success",
    type: "cargo",
  },
];
