import type { Mission } from "../types";

export const missions: Mission[] = [
  {
    id: 1,
    date: "May 16, 2026",
    name: "FalconSat",
    rocket: "Falcon 1",
    target: "Kepler-442 b",
    status: "success",
  },
  {
    id: 2,
    date: "Jun 02, 2026",
    name: "Dragon Demo",
    rocket: "Falcon 9",
    target: "Kepler-186 f",
    status: "aborted",
  },
  {
    id: 3,
    date: "Jun 18, 2026",
    name: "Starlink Batch 12",
    rocket: "Falcon 9",
    target: "Low Earth Orbit",
    status: "success",
  },
  {
    id: 4,
    date: "Jul 01, 2026",
    name: "Explorer IS1",
    rocket: "Explorer Heavy",
    target: "Kepler-452 b",
    status: "success",
  },
  {
    id: 5,
    date: "Jul 14, 2026",
    name: "Cargo Resupply CRS-3",
    rocket: "Falcon 9",
    target: "ISS",
    status: "aborted",
  },
  {
    id: 6,
    date: "Aug 03, 2026",
    name: "Voyager X",
    rocket: "Starship",
    target: "Kepler-22 b",
    status: "success",
  },
  {
    id: 7,
    date: "Aug 19, 2026",
    name: "Lunar Surveyor",
    rocket: "SLS",
    target: "Moon",
    status: "success",
  },
  {
    id: 8,
    date: "Sep 05, 2026",
    name: "Mars Cargo 1",
    rocket: "Starship",
    target: "Mars",
    status: "aborted",
  },
  {
    id: 9,
    date: "Sep 21, 2026",
    name: "Deep Space Probe",
    rocket: "Falcon Heavy",
    target: "Kepler-62 e",
    status: "success",
  },
  {
    id: 10,
    date: "Oct 10, 2026",
    name: "Habitat Deployment",
    rocket: "Starship",
    target: "Kepler-1649 c",
    status: "success",
  },
];
