import type { Mission } from "../types";

export const missions: Mission[] = [
  {
    id: 1,
    startDate: "May 16, 2026",
    endDate: "May 20, 2026",
    name: "FalconSat",
    rocket: "Falcon 1",
    target: "Kepler-442 b",
    status: "success",
    type: "cargo",
  },
  {
    id: 2,
    startDate: "Jun 02, 2026",
    endDate: "Jun 03, 2026",
    name: "Dragon Demo",
    rocket: "Falcon 9",
    target: "Kepler-186 f",
    status: "aborted",
    type: "cargo",
  },
  {
    id: 3,
    startDate: "Jun 18, 2026",
    endDate: "Jun 25, 2026",
    name: "Starlink Batch 12",
    rocket: "Falcon 9",
    target: "Low Earth Orbit",
    status: "success",
    type: "exploration",
  },
  {
    id: 4,
    startDate: "Jul 01, 2026",
    endDate: "Jul 10, 2026",
    name: "Explorer IS1",
    rocket: "Explorer Heavy",
    target: "Kepler-452 b",
    status: "success",
    type: "research",
  },
  {
    id: 5,
    startDate: "Jul 14, 2026",
    endDate: "Jul 15, 2026",
    name: "Cargo Resupply CRS-3",
    rocket: "Falcon 9",
    target: "ISS",
    status: "aborted",
    type: "exploration",
  },
  {
    id: 6,
    startDate: "Aug 03, 2026",
    endDate: "Aug 12, 2026",
    name: "Voyager X",
    rocket: "Starship",
    target: "Kepler-22 b",
    status: "success",
    type: "exploration",
  },
  {
    id: 7,
    startDate: "Aug 19, 2026",
    endDate: "Aug 28, 2026",
    name: "Lunar Surveyor",
    rocket: "SLS",
    target: "Moon",
    status: "success",
    type: "crewed",
  },
  {
    id: 8,
    startDate: "Sep 05, 2026",
    endDate: "Sep 06, 2026",
    name: "Mars Cargo 1",
    rocket: "Starship",
    target: "Mars",
    status: "aborted",
    type: "exploration",
  },
  {
    id: 9,
    startDate: "Sep 21, 2026",
    endDate: "Oct 01, 2026",
    name: "Deep Space Probe",
    rocket: "Falcon Heavy",
    target: "Kepler-62 e",
    status: "success",
    type: "cargo",
  },
  {
    id: 10,
    startDate: "Oct 10, 2026",
    endDate: "Oct 20, 2026",
    name: "Habitat Deployment",
    rocket: "Starship",
    target: "Kepler-1649 c",
    status: "success",
    type: "cargo",
  },
];

export const upcomingMissions: Mission[] = [
  {
    id: 1,
    startDate: "Nov 02, 2026",
    endDate: "Nov 08, 2026",
    name: "Orbital Relay Alpha",
    rocket: "Falcon 9",
    target: "Low Earth Orbit",
    status: "upcoming",
    type: "cargo",
  },
  {
    id: 2,
    startDate: "Nov 10, 2026",
    endDate: "Nov 18, 2026",
    name: "Deep Space Mapper",
    rocket: "Falcon Heavy",
    target: "Kepler-90 c",
    status: "upcoming",
    type: "research",
  },
  {
    id: 3,
    startDate: "Nov 22, 2026",
    endDate: "Nov 30, 2026",
    name: "Lunar Base Supply",
    rocket: "Starship",
    target: "Moon",
    status: "upcoming",
    type: "cargo",
  },
  {
    id: 4,
    startDate: "Dec 05, 2026",
    endDate: "Dec 12, 2026",
    name: "Europa Scanner",
    rocket: "Explorer Heavy",
    target: "Europa",
    status: "upcoming",
    type: "exploration",
  },
  {
    id: 5,
    startDate: "Dec 15, 2026",
    endDate: "Dec 22, 2026",
    name: "Crew Transfer CT-7",
    rocket: "SLS",
    target: "ISS",
    status: "upcoming",
    type: "crewed",
  },
  {
    id: 6,
    startDate: "Jan 04, 2027",
    endDate: "Jan 10, 2027",
    name: "Asteroid Mining Test",
    rocket: "Starship",
    target: "Asteroid Belt",
    status: "upcoming",
    type: "research",
  },
  {
    id: 7,
    startDate: "Jan 15, 2027",
    endDate: "Jan 25, 2027",
    name: "Mars Habitat Prep",
    rocket: "Starship",
    target: "Mars",
    status: "upcoming",
    type: "cargo",
  },
  {
    id: 8,
    startDate: "Feb 01, 2027",
    endDate: "Feb 07, 2027",
    name: "Solar Observatory",
    rocket: "Falcon 9",
    target: "Solar Orbit",
    status: "upcoming",
    type: "research",
  },
  {
    id: 9,
    startDate: "Feb 12, 2027",
    endDate: "Feb 20, 2027",
    name: "Titan Exploration Probe",
    rocket: "Falcon Heavy",
    target: "Titan",
    status: "upcoming",
    type: "exploration",
  },
  {
    id: 10,
    startDate: "Mar 01, 2027",
    endDate: "Mar 10, 2027",
    name: "Crew Mission CM-12",
    rocket: "SLS",
    target: "Moon",
    status: "upcoming",
    type: "crewed",
  },
];
