// import type { MissionDB } from "@common/types";

// export const missions: MissionDB[] = [
//   {
//     id: 1,
//     startDate: new Date("2026-04-29"),
//     endDate: new Date("2026-05-08"),
//     name: "Orbital Relay Alpha",
//     rocket: "Falcon 9",
//     target: "Low Earth Orbit",
//     type: "cargo",
//     customers: ["NASA", "ESA"],
//     isAborted: false,
//   },
//   {
//     id: 2,
//     startDate: new Date("2026-11-10"),
//     endDate: new Date("2026-11-18"),
//     name: "Deep Space Mapper",
//     rocket: "Falcon Heavy",
//     target: "Kepler-90 c",
//     type: "research",
//     customers: ["JAXA"],
//     isAborted: false,
//   },
//   {
//     id: 3,
//     startDate: new Date("2026-11-22"),
//     endDate: new Date("2026-11-30"),
//     name: "Lunar Base Supply",
//     rocket: "Starship",
//     target: "Moon",
//     type: "cargo",
//     customers: ["NASA", "SpaceX"],
//     isAborted: true,
//   },
//   {
//     id: 4,
//     startDate: new Date("2026-12-05"),
//     endDate: new Date("2026-12-12"),
//     name: "Europa Scanner",
//     rocket: "Explorer Heavy",
//     target: "Europa",
//     type: "exploration",
//     customers: ["ESA"],
//     isAborted: false,
//   },
//   {
//     id: 5,
//     startDate: new Date("2026-04-28"),
//     endDate: new Date("2026-06-01"),
//     name: "Crew Transfer CT-7",
//     rocket: "SLS",
//     target: "ISS",
//     type: "crewed",
//     customers: ["NASA"],
//     isAborted: false,
//   },
//   {
//     id: 6,
//     startDate: new Date("2026-04-04"),
//     endDate: new Date("2026-06-08"),
//     name: "Asteroid Mining Test",
//     rocket: "Starship",
//     target: "Asteroid Belt",
//     type: "research",
//     customers: ["SpaceX", "NASA"],
//     isAborted: false,
//   },
//   {
//     id: 7,
//     startDate: new Date("2027-01-15"),
//     endDate: new Date("2027-01-25"),
//     name: "Mars Habitat Prep",
//     rocket: "Starship",
//     target: "Mars",
//     type: "cargo",
//     customers: ["NASA", "Axiom"],
//     isAborted: false,
//   },
//   {
//     id: 8,
//     startDate: new Date("2026-04-30"),
//     endDate: new Date("2026-06-07"),
//     name: "Solar Observatory",
//     rocket: "Falcon 9",
//     target: "Solar Orbit",
//     type: "research",
//     customers: ["ESA", "JAXA"],
//     isAborted: false,
//   },
//   {
//     id: 9,
//     startDate: new Date("2026-05-29"),
//     endDate: new Date("2026-06-20"),
//     name: "Titan Exploration Probe",
//     rocket: "Falcon Heavy",
//     target: "Titan",
//     type: "exploration",
//     customers: ["JAXA", "ESA"],
//     isAborted: false,
//   },
//   {
//     id: 10,
//     startDate: new Date("2026-05-21"),
//     endDate: new Date("2027-06-28"),
//     name: "Crew Mission CM-12",
//     rocket: "SLS",
//     target: "Moon",
//     type: "crewed",
//     customers: ["NASA"],
//     isAborted: false,
//   },
//   {
//     id: 11,
//     startDate: new Date("2026-05-16"),
//     endDate: new Date("2026-05-20"),
//     name: "FalconSat",
//     rocket: "Falcon 1",
//     target: "Kepler-442 b",
//     type: "cargo",
//     customers: ["DARPA"],
//     isAborted: false,
//   },
//   {
//     id: 12,
//     startDate: new Date("2026-06-02"),
//     endDate: new Date("2026-06-03"),
//     name: "Dragon Demo",
//     rocket: "Falcon 9",
//     target: "Kepler-186 f",
//     type: "cargo",
//     customers: ["SpaceX"],
//     isAborted: true,
//   },
//   {
//     id: 13,
//     startDate: new Date("2026-06-18"),
//     endDate: new Date("2026-06-25"),
//     name: "Starlink Batch 12",
//     rocket: "Falcon 9",
//     target: "Low Earth Orbit",
//     type: "exploration",
//     customers: ["SpaceX"],
//     isAborted: true,
//   },
//   {
//     id: 14,
//     startDate: new Date("2026-07-01"),
//     endDate: new Date("2026-07-10"),
//     name: "Explorer IS1",
//     rocket: "Explorer Heavy",
//     target: "Kepler-452 b",
//     type: "research",
//     customers: ["ESA", "NASA"],
//     isAborted: true,
//   },
//   {
//     id: 15,
//     startDate: new Date("2026-07-14"),
//     endDate: new Date("2026-07-15"),
//     name: "Cargo Resupply CRS-3",
//     rocket: "Falcon 9",
//     target: "ISS",
//     type: "exploration",
//     customers: ["NASA"],
//     isAborted: false,
//   },
//   {
//     id: 16,
//     startDate: new Date("2026-08-03"),
//     endDate: new Date("2026-08-12"),
//     name: "Voyager X",
//     rocket: "Starship",
//     target: "Kepler-22 b",
//     type: "exploration",
//     customers: ["Blue Origin", "NASA"],
//     isAborted: false,
//   },
//   {
//     id: 17,
//     startDate: new Date("2026-08-19"),
//     endDate: new Date("2026-08-28"),
//     name: "Lunar Surveyor",
//     rocket: "SLS",
//     target: "Moon",
//     type: "crewed",
//     customers: ["NASA", "CSA"],
//     isAborted: true,
//   },
//   {
//     id: 18,
//     startDate: new Date("2026-09-05"),
//     endDate: new Date("2026-09-06"),
//     name: "Mars Cargo 1",
//     rocket: "Starship",
//     target: "Mars",
//     type: "exploration",
//     customers: ["SpaceX"],
//     isAborted: false,
//   },
//   {
//     id: 19,
//     startDate: new Date("2026-09-21"),
//     endDate: new Date("2026-10-01"),
//     name: "Deep Space Probe",
//     rocket: "Falcon Heavy",
//     target: "Kepler-62 e",
//     type: "cargo",
//     customers: ["JAXA", "ESA"],
//     isAborted: true,
//   },
//   {
//     id: 20,
//     startDate: new Date("2026-10-10"),
//     endDate: new Date("2026-10-20"),
//     name: "Habitat Deployment",
//     rocket: "Starship",
//     target: "Kepler-1649 c",
//     type: "cargo",
//     customers: ["NASA", "Axiom"],
//     isAborted: true,
//   },
// ];
